ETFs_Data = [
    {"nombre": "AZ China", "descripcion": "ETF que sigue el rendimiento del mercado chino", "simbolo": "ASHR"},
    {"nombre": "AZ MSCI Taiwan Index FD", "descripcion": "ETF que sigue el rendimiento del mercado de Taiwán", "simbolo": "EWT"},
    {"nombre": "AZ Russell 2000", "descripcion": "ETF que sigue el rendimiento del índice Russell 2000", "simbolo": "IWM"},
    {"nombre": "AZ Brasil", "descripcion": "ETF que sigue el rendimiento del mercado brasileño", "simbolo": "EWZ"},
    {"nombre": "AZ MSCI United Kingdom", "descripcion": "ETF que sigue el rendimiento del mercado del Reino Unido", "simbolo": "EWU"},
    {"nombre": "AZ DJ US Financial Sect", "descripcion": "ETF que sigue el rendimiento del sector financiero de EE.UU.", "simbolo": "IYF"},
    {"nombre": "AZ BRIC", "descripcion": "ETF que sigue el rendimiento de los mercados de Brasil, Rusia, India y China", "simbolo": "BKF"},
    {"nombre": "AZ MSCI South Korea Index", "descripcion": "ETF que sigue el rendimiento del mercado de Corea del Sur", "simbolo": "EWY"},
    {"nombre": "AZ Barclays Aggregate", "descripcion": "ETF que sigue el rendimiento de bonos agregados", "simbolo": "AGG"},
    {"nombre": "AZ Mercados Emergentes", "descripcion": "ETF que sigue el rendimiento de los mercados emergentes", "simbolo": "EEM"},
    {"nombre": "AZ MSCI EMU", "descripcion": "ETF que sigue el rendimiento de la zona euro (EMU)", "simbolo": "EZU"},
    {"nombre": "AZ FTSE/Xinhua China 25", "descripcion": "ETF que sigue el rendimiento de las principales empresas chinas", "simbolo": "FXI"},
    {"nombre": "AZ Oro", "descripcion": "ETF que sigue el rendimiento del oro", "simbolo": "GLD"},
    {"nombre": "AZ LATIXX MEX CETETRAC", "descripcion": "ETF que sigue el rendimiento de cetes en México", "simbolo": "MXX"},
    {"nombre": "AZ QQQ NASDAQ 100", "descripcion": "ETF que sigue el rendimiento del índice NASDAQ 100", "simbolo": "QQQ"},
    {"nombre": "AZ MSCI Asia Ex-Japan", "descripcion": "ETF que sigue el rendimiento del mercado asiático excluyendo Japón", "simbolo": "AAXJ"},
    {"nombre": "AZ LATIXX MEX M10TRAC", "descripcion": "ETF que sigue el rendimiento del índice M10 en México", "simbolo": "M10.MX"},
    {"nombre": "AZ Barclays 1-3 Year TR", "descripcion": "ETF que sigue el rendimiento de bonos a corto plazo", "simbolo": "SHY"},
    {"nombre": "AZ MSCI ACWI Index Fund", "descripcion": "ETF que sigue el rendimiento del índice global ACWI", "simbolo": "ACWI"},
    {"nombre": "AZ LATIXX Mexico M5TRAC", "descripcion": "ETF que sigue el rendimiento del índice M5 en México", "simbolo": "M5TRAC.MX"},
    {"nombre": "AZ Silver Trust", "descripcion": "ETF que sigue el rendimiento de la plata", "simbolo": "SLV"},
    {"nombre": "AZ MSCI Hong Kong Index", "descripcion": "ETF que sigue el rendimiento del mercado de Hong Kong", "simbolo": "EWH"},
    {"nombre": "AZ LATIXX MEX UDITRAC", "descripcion": "ETF que sigue el rendimiento del índice UDI en México", "simbolo": "UDITRAC.MX"},
    {"nombre": "AZ SPDR S&P 500 ETF Trust", "descripcion": "ETF que sigue el rendimiento del índice S&P 500", "simbolo": "SPY"},
    {"nombre": "AZ MSCI Japan Index FD", "descripcion": "ETF que sigue el rendimiento del mercado japonés", "simbolo": "EWJ"},
    {"nombre": "AZ BG EUR Govt Bond 1-3", "descripcion": "ETF que sigue el rendimiento de bonos gubernamentales europeos a corto plazo", "simbolo": "IBGE.MI"},
    {"nombre": "AZ SPDR DJIA Trust", "descripcion": "ETF que sigue el rendimiento del índice Dow Jones Industrial Average", "simbolo": "DIA"},
    {"nombre": "AZ MSCI France Index FD", "descripcion": "ETF que sigue el rendimiento del mercado francés", "simbolo": "EWQ"},
    {"nombre": "AZ DJ US Oil & Gas Expl", "descripcion": "ETF que sigue el rendimiento del sector de exploración de petróleo y gas en EE.UU.", "simbolo": "IEO"},
    {"nombre": "AZ Vanguard Emerging Market ETF", "descripcion": "ETF de Vanguard que sigue el rendimiento de mercados emergentes", "simbolo": "VWO"},
    {"nombre": "AZ MSCI Australia Index", "descripcion": "ETF que sigue el rendimiento del mercado australiano", "simbolo": "EWA"},
    {"nombre": "AZ IPC Large Cap T R TR", "descripcion": "ETF que sigue el rendimiento de las grandes empresas en México", "simbolo": "LCT.MX"},
    {"nombre": "AZ Financial Select Sector SPDR", "descripcion": "ETF que sigue el rendimiento del sector financiero de EE.UU.", "simbolo": "XLF"},
    {"nombre": "AZ MSCI Canada", "descripcion": "ETF que sigue el rendimiento del mercado canadiense", "simbolo": "EWC"},
    {"nombre": "AZ S&P Latin America 40", "descripcion": "ETF que sigue el rendimiento de las 40 principales empresas en América Latina", "simbolo": "ILF"},
    {"nombre": "AZ Health Care Select Sector", "descripcion": "ETF que sigue el rendimiento del sector de salud de EE.UU.", "simbolo": "XLV"},
    {"nombre": "AZ MSCI Germany Index", "descripcion": "ETF que sigue el rendimiento del mercado alemán", "simbolo": "EWG"},
    {"nombre": "AZ DJ US Home Construct", "descripcion": "ETF que sigue el rendimiento del sector de construcción en EE.UU.", "simbolo": "ITB"}
]
